# Generated by Django 3.2 on 2023-02-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_userdayfood_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayfood',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
