# Generated by Django 3.2 on 2023-02-14 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_userdayfood_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayfood',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ResultDayDci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('calories', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_day_dci', to='model.user')),
            ],
        ),
    ]
