# Generated by Django 3.2 on 2023-02-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20230214_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='cur_day_dci',
        ),
    ]
