# Generated by Django 3.2 on 2023-02-27 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_remove_targetuser_cur_day_dci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultdaydci',
            name='time',
        ),
        migrations.AddField(
            model_name='resultdaydci',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
