# Generated by Django 3.2 on 2023-03-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20230227_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetuser',
            name='cur_week',
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='cur_week_noraml_dci',
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='period',
        ),
        migrations.RemoveField(
            model_name='targetuser',
            name='programm_ready',
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('start_dci', models.IntegerField(blank=True, default=0, null=True)),
                ('cur_dci', models.IntegerField(blank=True, default=0, null=True)),
                ('phase1', models.IntegerField(blank=True, default=0, null=True)),
                ('phase2', models.IntegerField(blank=True, default=0, null=True)),
                ('cur_day', models.IntegerField(blank=True, default=0, null=True)),
                ('cur_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='model.user')),
            ],
        ),
    ]
