# Generated by Django 3.2 on 2023-03-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_targetuser_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdaydci',
            name='cur_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultdaydci',
            name='deficit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
