# Generated by Django 3.2 on 2023-03-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_auto_20230316_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogram',
            name='achievement',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
