# Generated by Django 3.2 on 2023-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_userprogram_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogram',
            name='percentage_decrease',
            field=models.IntegerField(default=15),
        ),
    ]
