# Generated by Django 3.2 on 2023-03-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_userprogram_percentage_decrease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogram',
            name='percentage_decrease',
        ),
        migrations.AddField(
            model_name='targetuser',
            name='percentage_decrease',
            field=models.IntegerField(default=15),
        ),
    ]
