# Generated by Django 3.2 on 2023-03-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='stage',
        ),
        migrations.AddField(
            model_name='message',
            name='mesKey',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
