# Generated by Django 3.2 on 2023-03-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_auto_20230320_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstageguide',
            name='stage',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
