# Generated by Django 3.2 on 2023-03-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_alter_userstageguide_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mesKey',
            field=models.CharField(max_length=50),
        ),
    ]
