# Generated by Django 3.2 on 2023-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_alter_message_meskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
