# Generated by Django 3.2 on 2023-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_message_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datetime_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
