# Generated by Django 3.2 on 2023-03-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0019_auto_20230322_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminduser',
            name='remind_first',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reminduser',
            name='remind_second',
            field=models.BooleanField(default=True),
        ),
    ]
