# Generated by Django 3.2 on 2023-03-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_auto_20230322_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuser',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
    ]
