# Generated by Django 3.2 on 2023-03-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_targetuser_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminduser',
            name='day_without_indication_weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
