# Generated by Django 3.2 on 2023-03-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0022_reminduser_day_without_indication_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminduser',
            name='remind_weight',
            field=models.BooleanField(default=True),
        ),
    ]
