# Generated by Django 3.2 on 2023-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0023_reminduser_remind_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdaydci',
            name='cur_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='cur_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='target_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='cur_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
